sudo: required
services:
  - docker

before_install:
  - docker build -t vladmois/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vladmois/react-test npm test

after_success:
  - docker build -t vladmois/multi-client ./client
  - docker build -t vladmois/multi-nginx ./nginx
  - docker build -t vladmois/multi-server ./server
  - docker build -t vladmois/multi-worker ./worker
  # Log in to the docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to the dockerhub.
  - docker push vladmois/multi-client
  - docker push vladmois/multi-nginx
  - docker push vladmois/multi-server
  - docker push vladmois/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-000274619788
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
